### PR TITLE
Some game scaffolding 

### PR DESCRIPTION
**Pull request by rraub**
Webpack, jquery, twitter bootstrap.. should we add anything else? @nathan-rollins

### CODE REVIEW

**Comment by rraub** [comment]
should we add jslint? I'm leaning towards yes..

**Comment by ndrollin** [comment]
I concur on jslint.

**Comment by ndrollin** [comment]
JSLint or ESLint? It might be easier for projects like this and Carbon Clicker to just stick with jshint.

**Comment by rraub** [comment]
I have a slight preference for ESLint since its got more support going forward and who knows maybe they might want to use ES6 👍

**Comment by rraub** [comment]
alright if theres nothing else that you can think of @nathan-rollins then merge it and I'll duplicate this for the other repo as well.

**Pull request merged**
